"""add otp fields to customers

Revision ID: 71956dcf96fe
Revises: c6f3fbd72a37
Create Date: 2026-07-15 03:54:56.475796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71956dcf96fe'
down_revision: Union[str, None] = 'c6f3fbd72a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('customers', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'otp_expires_at')
    op.drop_column('customers', 'otp_code')
    # ### end Alembic commands ###
